CANDIDATE_POOL = [
    {
        "id": "C001",
        "name": "Arjun Sharma",
        "title": "Senior Backend Engineer",
        "experience_years": 6,
        "skills": ["Python", "FastAPI", "Django", "PostgreSQL", "Redis", "Docker", "Kubernetes", "AWS", "Microservices", "Kafka"],
        "location": "Bangalore, India",
        "work_mode_preference": "Hybrid",
        "current_company": "Flipkart",
        "education": "B.Tech Computer Science, IIT Bombay",
        "availability": "2 months notice",
        "salary_expectation": "₹35–45 LPA",
        "bio": "Backend engineer with strong distributed systems experience. Led migration of monolith to microservices serving 10M+ users. Passionate about performance optimization.",
        "open_to_new_roles": True,
        "github": "github.com/arjun-sharma-dev",
        "achievements": ["Reduced API latency by 60%", "Mentored 5 junior engineers", "Open source contributor to FastAPI"]
    },
    {
        "id": "C002",
        "name": "Priya Nair",
        "title": "ML Engineer",
        "experience_years": 4,
        "skills": ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "MLflow", "Spark", "SQL", "GCP", "Hugging Face", "LLMs"],
        "location": "Hyderabad, India",
        "work_mode_preference": "Remote",
        "current_company": "Google",
        "education": "M.Tech AI/ML, IIT Hyderabad",
        "availability": "3 months notice",
        "salary_expectation": "₹40–55 LPA",
        "bio": "ML Engineer at Google working on recommendation systems. Recently upskilled into LLMs and RAG pipelines. Published 2 papers on NLP.",
        "open_to_new_roles": False,
        "github": "github.com/priya-ml",
        "achievements": ["Built recommendation system serving 50M users", "Published in ACL 2024", "Google ML Champion award"]
    },
    {
        "id": "C003",
        "name": "Rahul Mehta",
        "title": "Full Stack Developer",
        "experience_years": 3,
        "skills": ["React", "Node.js", "TypeScript", "MongoDB", "GraphQL", "AWS", "Tailwind CSS", "Next.js", "Jest"],
        "location": "Mumbai, India",
        "work_mode_preference": "Remote",
        "current_company": "Razorpay",
        "education": "B.E. Information Technology, VJTI Mumbai",
        "availability": "1 month notice",
        "salary_expectation": "₹18–25 LPA",
        "bio": "Full stack developer at Razorpay working on payment dashboards. Strong in React ecosystem and building real-time applications.",
        "open_to_new_roles": True,
        "github": "github.com/rahul-fullstack",
        "achievements": ["Built real-time payment monitoring dashboard", "Reduced frontend load time by 45%", "Led team of 4 developers"]
    },
    {
        "id": "C004",
        "name": "Sneha Reddy",
        "title": "Product Manager",
        "experience_years": 5,
        "skills": ["Product Strategy", "Agile", "JIRA", "Figma", "SQL", "A/B Testing", "User Research", "Roadmapping", "Stakeholder Management"],
        "location": "Bangalore, India",
        "work_mode_preference": "Hybrid",
        "current_company": "PhonePe",
        "education": "MBA, IIM Calcutta; B.Tech, BITS Pilani",
        "availability": "2 months notice",
        "salary_expectation": "₹30–40 LPA",
        "bio": "PM at PhonePe managing the merchant onboarding product. Shipped 12 features in the last year with measurable business impact.",
        "open_to_new_roles": True,
        "github": None,
        "achievements": ["Grew merchant base by 35%", "Launched UPI Autopay feature (10M+ users)", "Led cross-functional team of 20"]
    },
    {
        "id": "C005",
        "name": "Vikram Singh",
        "title": "DevOps / Cloud Engineer",
        "experience_years": 7,
        "skills": ["AWS", "Terraform", "Kubernetes", "Docker", "Jenkins", "Prometheus", "Grafana", "Ansible", "Linux", "Python", "CI/CD"],
        "location": "Pune, India",
        "work_mode_preference": "Remote",
        "current_company": "ThoughtWorks",
        "education": "B.Tech, NIT Surathkal",
        "availability": "Immediately available",
        "salary_expectation": "₹28–38 LPA",
        "bio": "Senior DevOps engineer with 7 years building cloud infrastructure. AWS certified solutions architect. Recently left ThoughtWorks and actively looking.",
        "open_to_new_roles": True,
        "github": "github.com/vikram-devops",
        "achievements": ["Reduced infra costs by 40% through right-sizing", "Built zero-downtime deployment pipeline", "AWS 3x certified"]
    },
    {
        "id": "C006",
        "name": "Ananya Krishnan",
        "title": "Data Scientist",
        "experience_years": 5,
        "skills": ["Python", "R", "Pandas", "NumPy", "Scikit-learn", "Tableau", "SQL", "Statistics", "Time Series", "XGBoost"],
        "location": "Chennai, India",
        "work_mode_preference": "Hybrid",
        "current_company": "HDFC Bank",
        "education": "M.Sc Statistics, Chennai Mathematical Institute",
        "availability": "2 months notice",
        "salary_expectation": "₹22–30 LPA",
        "bio": "Data scientist in banking domain, specializing in credit risk modeling and fraud detection. Strong statistical foundations.",
        "open_to_new_roles": True,
        "github": "github.com/ananya-ds",
        "achievements": ["Built fraud detection model saving ₹50Cr annually", "Reduced credit default rates by 15%", "Internal data science mentor"]
    },
    {
        "id": "C007",
        "name": "Karan Patel",
        "title": "Frontend Engineer",
        "experience_years": 4,
        "skills": ["React", "Vue.js", "TypeScript", "CSS", "Webpack", "Storybook", "Figma", "Performance optimization", "Web Accessibility"],
        "location": "Ahmedabad, India",
        "work_mode_preference": "Remote",
        "current_company": "Freshworks",
        "education": "B.Tech, DAIICT Gandhinagar",
        "availability": "6 weeks notice",
        "salary_expectation": "₹20–28 LPA",
        "bio": "Frontend engineer obsessed with UI performance and accessibility. Maintains a popular open-source React component library with 3k stars.",
        "open_to_new_roles": True,
        "github": "github.com/karan-ui",
        "achievements": ["Open source library 3k GitHub stars", "Lighthouse score 98+ on all company products", "Speaker at ReactConf India 2024"]
    },
    {
        "id": "C008",
        "name": "Meera Iyer",
        "title": "Senior Data Engineer",
        "experience_years": 6,
        "skills": ["Apache Spark", "Kafka", "Airflow", "dbt", "Snowflake", "Python", "SQL", "AWS Glue", "Data Modeling", "Delta Lake"],
        "location": "Bangalore, India",
        "work_mode_preference": "Hybrid",
        "current_company": "Swiggy",
        "education": "B.Tech, RVCE Bangalore",
        "availability": "2 months notice",
        "salary_expectation": "₹32–42 LPA",
        "bio": "Senior data engineer building real-time data pipelines at Swiggy. Expert in lakehouse architecture. Migrated legacy ETL to Spark saving 70% compute costs.",
        "open_to_new_roles": True,
        "github": "github.com/meera-data",
        "achievements": ["Built real-time order analytics pipeline (1M+ events/hr)", "Reduced data pipeline failures by 80%", "Data engineering blog: 10k readers/month"]
    },
    {
        "id": "C009",
        "name": "Siddharth Rao",
        "title": "Engineering Manager",
        "experience_years": 10,
        "skills": ["Team Leadership", "System Design", "Python", "Java", "Agile", "Technical Roadmap", "Hiring", "OKRs", "Cross-functional collaboration"],
        "location": "Bangalore, India",
        "work_mode_preference": "Hybrid",
        "current_company": "Amazon",
        "education": "B.Tech, IIT Delhi",
        "availability": "3 months notice",
        "salary_expectation": "₹60–80 LPA",
        "bio": "Engineering Manager at Amazon leading a team of 12 engineers on AWS billing systems. Previously IC engineer for 7 years. Strong people manager.",
        "open_to_new_roles": False,
        "github": None,
        "achievements": ["Built team from 4 to 12 engineers", "Delivered ₹200Cr revenue feature on time", "99.99% uptime for billing systems"]
    },
    {
        "id": "C010",
        "name": "Divya Menon",
        "title": "UX Designer",
        "experience_years": 4,
        "skills": ["Figma", "Adobe XD", "User Research", "Prototyping", "Design Systems", "Usability Testing", "Information Architecture", "Motion Design"],
        "location": "Kochi, India",
        "work_mode_preference": "Remote",
        "current_company": "Zoho",
        "education": "B.Des, NID Ahmedabad",
        "availability": "1 month notice",
        "salary_expectation": "₹18–25 LPA",
        "bio": "UX designer at Zoho focused on enterprise SaaS products. Strong portfolio in B2B design. Conducted 50+ user research sessions.",
        "open_to_new_roles": True,
        "github": None,
        "achievements": ["Redesigned CRM UI — increased task completion rate by 40%", "Created Zoho's enterprise design system", "Behance portfolio: 15k views"]
    },
    {
        "id": "C011",
        "name": "Aditya Kumar",
        "title": "Backend Engineer",
        "experience_years": 2,
        "skills": ["Node.js", "Express", "MongoDB", "REST APIs", "Git", "AWS basics", "Docker basics"],
        "location": "Noida, India",
        "work_mode_preference": "Onsite",
        "current_company": "TCS",
        "education": "B.Tech, DTU Delhi",
        "availability": "1 month notice",
        "salary_expectation": "₹8–12 LPA",
        "bio": "Junior backend developer with 2 years at TCS. Looking to move to a product company for more impactful work.",
        "open_to_new_roles": True,
        "github": "github.com/aditya-dev",
        "achievements": ["Delivered 3 client projects on time", "Internal hackathon winner 2023"]
    },
    {
        "id": "C012",
        "name": "Kavitha Subramaniam",
        "title": "ML Research Engineer",
        "experience_years": 3,
        "skills": ["Python", "PyTorch", "Transformers", "RLHF", "LLM fine-tuning", "RAG", "LangChain", "Vector DBs", "Prompt Engineering"],
        "location": "Bangalore, India",
        "work_mode_preference": "Remote",
        "current_company": "Sarvam AI",
        "education": "M.S. Computer Science, IISc Bangalore",
        "availability": "1 month notice",
        "salary_expectation": "₹30–45 LPA",
        "bio": "ML researcher at Sarvam AI working on Indian language LLMs. Expert in fine-tuning and RAG pipelines. Strong research background with practical production focus.",
        "open_to_new_roles": True,
        "github": "github.com/kavitha-ml",
        "achievements": ["Co-built Sarvam-1 Indian language model", "Published at EMNLP 2024", "Open source RAG toolkit 2k stars"]
    },
    {
        "id": "C013",
        "name": "Rohit Bansal",
        "title": "Product Manager",
        "experience_years": 3,
        "skills": ["Product Management", "Growth", "SQL", "Analytics", "Figma basics", "Customer interviews", "PRDs", "Go-to-market"],
        "location": "Delhi, India",
        "work_mode_preference": "Hybrid",
        "current_company": "Meesho",
        "education": "MBA, IIM Lucknow",
        "availability": "2 months notice",
        "salary_expectation": "₹22–30 LPA",
        "bio": "PM at Meesho focused on seller growth. Running growth experiments across acquisition and retention. Data-driven decision maker.",
        "open_to_new_roles": True,
        "github": None,
        "achievements": ["Grew seller base by 50% in 6 months", "Launched seller app feature used by 2M sellers", "PM of the Quarter — Q3 2024"]
    },
    {
        "id": "C014",
        "name": "Nisha Agarwal",
        "title": "Cloud Architect",
        "experience_years": 9,
        "skills": ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "Security", "Compliance", "Cost optimization", "Python", "Solution Design"],
        "location": "Hyderabad, India",
        "work_mode_preference": "Hybrid",
        "current_company": "Infosys",
        "education": "B.Tech, JNTU; AWS Certified Solutions Architect Professional",
        "availability": "3 months notice",
        "salary_expectation": "₹45–60 LPA",
        "bio": "Senior cloud architect at Infosys with 9 years experience designing multi-cloud solutions for Fortune 500 companies. Expert in cloud security and cost governance.",
        "open_to_new_roles": True,
        "github": None,
        "achievements": ["Architected cloud migration for 3 Fortune 500 clients", "Saved $2M annually in cloud costs for a US retail client", "AWS Community Hero"]
    },
    {
        "id": "C015",
        "name": "Akash Verma",
        "title": "Android Developer",
        "experience_years": 5,
        "skills": ["Kotlin", "Android SDK", "Jetpack Compose", "MVVM", "Room DB", "Coroutines", "Firebase", "REST APIs", "Unit testing"],
        "location": "Pune, India",
        "work_mode_preference": "Remote",
        "current_company": "Ola",
        "education": "B.Tech, Pune University",
        "availability": "6 weeks notice",
        "salary_expectation": "₹22–32 LPA",
        "bio": "Senior Android developer at Ola with 5 years building consumer apps. Expert in Jetpack Compose. App with 50M+ downloads on Play Store.",
        "open_to_new_roles": True,
        "github": "github.com/akash-android",
        "achievements": ["Ola app 50M+ downloads, 4.6 rating", "Migrated entire app to Jetpack Compose", "Play Store featured app 2023"]
    }
]
